export const UPDATE_LOGIN_STATUS = 'UPDATE_LOGIN_STATUS'
export const SET_LIKE_LIST = 'SET_LIKE_LIST'
export const UPDATE_RECENT_PLAYLIST = 'UPDATE_RECENT_PLAYLIST'

// 音乐播放
export const SET_SONG_INFO = 'SET_SONG_INFO'
export const SET_ISPLAYING = 'SET_ISPLAYING'
export const SET_CURRENTTIME = 'SET_CURRENTTIME'
export const SET_TOTALTIME = 'SET_TOTALTIME'
